"""Render Act 2.5 of the Rytmi demo video — the kizomba example case.

Sits in the master between Act 2 (architecture) and Act 3a (the four
Gemma panels for Filomena). Two purposes:

1. Name the example song's style explicitly for any viewer who doesn't
   know what kizomba is — so the next 90 s of Filomena content has a
   genre frame.
2. Make the failure mode of generic beat trackers *audible*, not just
   stated. This is the beat that used to live in old Act 1 caption 2
   (kizomba's pulse is subtle / clicks overlay); it lands much better
   here, after the architecture has been set up and right before the
   Gemma panels do their work on the same song.

Sequence (with 0.5 s xfade between scenes):

- caption 1 (~5.0 s, silent): *"Example case: kizomba."* /
  *"An Afro-Latin partner-dance style where the pulse a dancer steps on
  hides behind a syncopated kick."*
- caption 2 (~7.0 s, with `act1_filomena_hook_clicks.wav` audible
  underneath): *"Generic beat trackers misfire here."* footer
  *"Filomena Maricoa — Teu Toque · clicks below show a generic tracker's
  wrong guesses · listen to the bassline for the real pulse."*

Output: ``demo_assets/output/act2_5_kizomba_intro.mp4``  (1920×1080 /
30 fps / h264 + aac).

Re-runnable: re-renders the caption PNGs each call.

Usage from repo root::

    .venv/bin/python demo_assets/scripts/make_act2_5_video.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "demo_assets" / "scripts"))

from make_caption_slide import render_caption_slide  # noqa: E402

OUTPUT_DIR = ROOT / "demo_assets" / "output"

# Audio asset reused from the original Act 1 clicks-overlay build.
# `act1_*` filename kept on disk for backward compatibility — it was
# generated by `make_all_demo_clips.py` and there was no reason to
# rename the file just because the beat moved acts.
CLICKS_WAV = OUTPUT_DIR / "act1_filomena_hook_clicks.wav"

OUTPUT_PATH = OUTPUT_DIR / "act2_5_kizomba_intro.mp4"

CAPTION_PNG_1 = OUTPUT_DIR / "_act2_5_caption1.png"
CAPTION_PNG_2 = OUTPUT_DIR / "_act2_5_caption2.png"

XFADE_S = 0.5
WIDTH = 1920
HEIGHT = 1080
FPS = 30


@dataclass(frozen=True)
class Scene:
    png: Path
    visible_s: float
    label: str


# Visible-second budget — 2 scenes with one 0.5 s xfade:
#   total = 5.0 + (0.5 + 7.0) = 12.5 s
SCENES: list[Scene] = [
    Scene(CAPTION_PNG_1, visible_s=5.0, label="caption1 (kizomba name + style gloss)"),
    Scene(CAPTION_PNG_2, visible_s=7.0, label="caption2 (audible misfire)"),
]

# Audio timing: the clicks WAV starts at the moment caption 2 reaches
# full visibility — running-output time = visible_s of scene 1 + the
# half-second crossfade.
AUDIO_DELAY_MS = int((SCENES[0].visible_s + XFADE_S) * 1000)


def _render_caption_pngs() -> None:
    """Render the two caption slides. Idempotent."""
    render_caption_slide(
        primary="Example case: kizomba.",
        secondary=(
            "An Afro-Latin partner-dance style where the pulse a dancer "
            "steps on hides behind a syncopated kick."
        ),
        footer=None,
        output=CAPTION_PNG_1,
        width=WIDTH,
        height=HEIGHT,
        primary_pt=92,
        secondary_pt=46,
    )
    render_caption_slide(
        primary="Generic beat trackers misfire here.",
        secondary=None,
        footer=(
            "Filomena Maricoa — Teu Toque  ·  clicks below show a generic "
            "tracker's wrong guesses  ·  listen to the bassline for the real pulse"
        ),
        output=CAPTION_PNG_2,
        width=WIDTH,
        height=HEIGHT,
        primary_pt=80,
        secondary_pt=46,
        footer_pt=28,
    )


def _build_filter_graph(scenes: list[Scene], xfade_s: float) -> tuple[str, float]:
    """Build the xfade chain — same pattern as `make_act{1,2}_video`."""
    n = len(scenes)
    if n == 0:
        raise ValueError("no scenes")

    parts: list[str] = []
    for i, _ in enumerate(scenes):
        parts.append(
            f"[{i}:v]scale={WIDTH}:{HEIGHT}:force_original_aspect_ratio=decrease,"
            f"pad={WIDTH}:{HEIGHT}:(ow-iw)/2:(oh-ih)/2:color=0x0f172a,"
            f"setsar=1,fps={FPS},format=yuv420p[s{i}]"
        )

    if n == 1:
        parts.append("[s0]null[v]")
        return ";".join(parts), scenes[0].visible_s

    last_label = "s0"
    running_offset = scenes[0].visible_s
    for i in range(1, n):
        next_label = f"v{i}"
        parts.append(
            f"[{last_label}][s{i}]xfade=transition=fade"
            f":duration={xfade_s}:offset={running_offset:.3f}[{next_label}]"
        )
        last_label = next_label
        running_offset += xfade_s + scenes[i].visible_s

    parts.append(f"[{last_label}]null[v]")
    return ";".join(parts), running_offset


def _ffmpeg_cmd(
    scenes: list[Scene], audio_path: Path, audio_delay_ms: int, total_s: float
) -> list[str]:
    cmd: list[str] = ["ffmpeg", "-y"]

    n = len(scenes)
    for i, scene in enumerate(scenes):
        if not scene.png.exists():
            raise FileNotFoundError(scene.png)
        pad = XFADE_S if i < n - 1 else 0.0
        input_dur = scene.visible_s + pad + 0.5  # +0.5 s safety
        cmd.extend(["-loop", "1", "-t", f"{input_dur:.3f}", "-i", str(scene.png)])

    if not audio_path.exists():
        raise FileNotFoundError(audio_path)
    cmd.extend(["-i", str(audio_path)])

    video_filter, _computed_total = _build_filter_graph(scenes, XFADE_S)
    audio_index = n  # zero-based input index for the audio file

    # Audio chain: delay clicks until caption 2 lands, then pad with
    # silence to fill out the act so -map doesn't truncate the video early.
    audio_filter = (
        f"[{audio_index}:a]aresample=44100,aformat=channel_layouts=stereo,"
        f"adelay={audio_delay_ms}|{audio_delay_ms},"
        f"apad,atrim=0:{total_s:.3f},asetpts=PTS-STARTPTS[a]"
    )
    filter_complex = f"{video_filter};{audio_filter}"

    cmd.extend([
        "-filter_complex", filter_complex,
        "-map", "[v]",
        "-map", "[a]",
        "-t", f"{total_s:.3f}",
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-r", str(FPS),
        "-c:a", "aac",
        "-b:a", "192k",
        "-movflags", "+faststart",
        str(OUTPUT_PATH),
    ])
    return cmd


def main() -> int:
    if shutil.which("ffmpeg") is None:
        print("ERROR: ffmpeg not found on PATH.", file=sys.stderr)
        return 2
    if not CLICKS_WAV.exists():
        print(f"ERROR: missing prerequisite: {CLICKS_WAV}", file=sys.stderr)
        print("  Run `make_all_demo_clips.py` to generate the clicks overlay.",
              file=sys.stderr)
        return 2

    print("Rendering caption PNGs …")
    _render_caption_pngs()

    _, total_s = _build_filter_graph(SCENES, XFADE_S)
    print(f"Scenes ({len(SCENES)}), total video = {total_s:.2f} s:")
    for s in SCENES:
        print(f"  {s.label}  visible {s.visible_s:.2f} s  ({s.png.name})")
    print(f"Audio: clicks delayed by {AUDIO_DELAY_MS / 1000:.1f} s, then padded.")

    cmd = _ffmpeg_cmd(SCENES, CLICKS_WAV, AUDIO_DELAY_MS, total_s)
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        print(f"ffmpeg exited with code {result.returncode}", file=sys.stderr)
        return result.returncode

    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
