"""Probe Gemma 4 audio (E4B) on short kizomba excerpts.

Asks the multimodal model to describe rhythmic/musical feel of three short
clips and compares those answers against what our DSP+text pipeline already
says. The point is to find out whether the audio model adds *novel* signal —
song-specific musicality language that the text-only pipeline can't access —
or whether it produces the same generic kizomba boilerplate.

This piggybacks on the existing ``rytmi.transcribe.load_multimodal_model``
loader and adds rhythm-oriented prompts instead of the language/lyrics
prompts ``transcribe_vocals`` uses.

WARNING: loads ``google/gemma-4-E4B-it`` (~9 GB on disk, several GB of GPU
memory). First run is slow because the weights download. Subsequent runs
hit the HF cache. If you don't have GPU bandwidth for this, skip it — the
script is here so the experiment is repeatable, not required.

Run from repo root:
    .venv/bin/python demo_assets/scripts/probe_gemma_audio.py

Output goes to ``demo_assets/output/gemma_audio_probe.md`` so you can read
it later without re-running the model.
"""

from __future__ import annotations

import sys
import warnings
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))


# (song path relative to repo root, label, start_s, duration_s, what we want
# Gemma to comment on)
CLIPS: list[tuple[str, str, float, float, str]] = [
    (
        "data/songs/eval_set/kizomba/Filomena_Maricoa_-_Teu_Toque_Official_Video [sKbWzD0mt6I].mp3",
        "Filomena — main section (clear pulse, ~92 BPM)",
        32.0, 12.0,
        "main section with full vocal and bass",
    ),
    (
        "data/songs/eval_set/kizomba/Charbel_-_E_Magia_Ben_Ana [6McenE8gUqM].mp3",
        "E_Magia Ben Ana — break (intermittent vocal, low percussion)",
        145.0, 12.0,
        "the break where percussion thins out",
    ),
    (
        "data/songs/eval_set/kizomba/Tony_Pirata_Lydia_Laprade_Filomena_Maricoa_-_Teu_Toque [^.]*.mp3",
        "Tony_Pirata — pre-break build",
        125.0, 12.0,
        "the bar before the break drops",
    ),
]


# Two prompts per clip. We deliberately ask one open-ended musicality question
# and one targeted dancer-coaching question, to see if the model adds anything
# beyond DSP categories on either axis.
PROMPTS = [
    (
        "musicality",
        "You are a kizomba dance teacher. In two short sentences, describe what "
        "is happening *musically* in this clip in a way a learner could feel. "
        "Be specific to this clip, not generic. Avoid metric values like BPM.",
    ),
    (
        "dancer_cue",
        "You are a kizomba dance teacher. In one short sentence, give a learner "
        "one concrete movement cue for what to do *during this exact clip*. "
        "Reference what you actually hear, not generic kizomba advice.",
    ),
]


def _resolve_clip_paths() -> list[tuple[Path, str, float, float, str]]:
    import glob as _glob
    out = []
    for pat, label, start, dur, ctx in CLIPS:
        # `glob.escape` keeps literal `[YouTubeID]` brackets intact instead
        # of treating them as character classes. We then re-introduce a single
        # wildcard for the Tony_Pirata case where the filename was unknown
        # at script-write time (`[^.]*` placeholder in CLIPS).
        if "[^.]*" in pat:
            head, _, tail = pat.partition("[^.]*")
            search = _glob.escape(head) + "*" + _glob.escape(tail)
        else:
            search = _glob.escape(pat)
        matches = sorted(_glob.glob(str(ROOT / search)))
        if not matches:
            print(f"  SKIP (not found): {pat}")
            continue
        out.append((Path(matches[0]), label, start, dur, ctx))
    return out


def main() -> int:
    try:
        from rytmi.audio import load_audio, slice_audio
        from rytmi.transcribe import load_multimodal_model
        import numpy as np
        import torch
    except ImportError as exc:
        print(f"ERROR: missing dependency: {exc}", file=sys.stderr)
        return 1

    clips = _resolve_clip_paths()
    if not clips:
        print("No source clips found. Aborting.", file=sys.stderr)
        return 1

    print(f"Loading Gemma 4 multimodal (E4B). This is slow on first run...")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        processor, model = load_multimodal_model()

    out_path = ROOT / "demo_assets" / "output" / "gemma_audio_probe.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = ["# Gemma 4 audio probe — kizomba excerpts\n"]
    lines.append(
        "Generated by `demo_assets/scripts/probe_gemma_audio.py`. The point "
        "is to see whether Gemma 4 audio adds song-specific musicality "
        "language beyond what DSP categories already give us.\n"
    )

    AUDIO_SR = 16000
    for clip_path, label, start, dur, ctx in clips:
        print(f"\n=== {label} ===")
        lines.append(f"\n## {label}\n")
        lines.append(f"- Source: `{clip_path.name}`")
        lines.append(f"- Window: {start:.0f}s + {dur:.0f}s")
        lines.append(f"- Context: {ctx}\n")

        audio = load_audio(str(clip_path))
        sub = slice_audio(audio, start, dur)
        # Resample to 16 kHz mono for Gemma audio.
        from rytmi.transcribe import _resample_to
        clip_samples = _resample_to(sub.samples, sub.sr, AUDIO_SR)

        for prompt_label, prompt_text in PROMPTS:
            messages = [{
                "role": "user",
                "content": [
                    {"type": "audio", "audio": clip_samples},
                    {"type": "text", "text": prompt_text},
                ],
            }]
            inputs = processor.apply_chat_template(
                messages,
                add_generation_prompt=True,
                tokenize=True,
                return_tensors="pt",
                return_dict=True,
            )
            from rytmi.llm import _select_input_device
            device = _select_input_device(model, torch)
            inputs = {k: (v.to(device) if hasattr(v, "to") else v) for k, v in inputs.items()}
            input_len = inputs["input_ids"].shape[-1]
            with torch.inference_mode():
                output_ids = model.generate(
                    **inputs, max_new_tokens=120, do_sample=False,
                )
            text = processor.batch_decode(
                output_ids[:, input_len:], skip_special_tokens=True
            )[0].strip()
            print(f"\n[{prompt_label}]")
            print(text)
            lines.append(f"### Prompt: {prompt_label}\n")
            lines.append(f"> {prompt_text}\n")
            lines.append(f"```\n{text}\n```\n")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
